environment: test
slice_dir: ./slice-data # ground truth
input_dir: ./dirty-data # dirty table
llm_work_dir: './chat'
code_work_dir: './code' # save the scripts
report_dir: './report'
log_dir: './log'
openai_config:
  # base_url, no need to set
  api_key: sk-xxxxx
  model: gpt-4-turbo  # or gpt-4 / gpt-4-1106-preview
  temperature: 0