environment: test
slice_dir: ./slice-data # ground truth
input_dir: ./input-data # dirty table
prompt_type: sketch # or cot
sketch_work_dir: './sketch'
agent_work_dir: './agent' # save the scripts
openai_config:
  # base_url, no need to set
  api_key: sk-xxxxx
  model: gpt-4-turbo  # or gpt-4 / gpt-4-1106-preview
  temperature: 0