environment: development
llm_zoo:
  common:
    temperature: 0.0
    ctx_token: 2048 # max 4096 for gpt-4-turbo
  openai:
    api_key: sk-
    model: gpt-4-turbo  # or gpt-3.5-turbo-1106 / gpt-4-1106-preview
  ollama:
    model: llama3 # llama2， gemma
llm_output_dir: ./examples/abc
